version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      DB_URI: mongodb://mongodb:27017/graund
    restart: always

  mongodb:
    image: mongo:8.0.9
    container_name: mongodb
    ports: 
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
